/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadevendas.view;

import java.sql.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemadevendas.controller.ClienteController;
import sistemadevendas.controller.NotaFiscalController;
import sistemadevendas.controller.ProdutoController;
import sistemadevendas.exceptions.AtualizacaoEstoqueNegativaException;
import sistemadevendas.exceptions.FalhaClienteException;
import sistemadevendas.exceptions.FalhaNotaFiscalException;
import sistemadevendas.exceptions.FalhaProdutoException;
import sistemadevendas.exceptions.NaoEncontradoException;
import sistemadevendas.model.Cliente;
import sistemadevendas.model.NotaFiscal;
import sistemadevendas.model.Produto;
import sistemadevendas.services.ClienteService;
import sistemadevendas.services.ProdutoService;

/**
 *
 * @author aluno
 */
public class NotaFiscalView extends javax.swing.JFrame {

    /**
     * Creates new form ItemNotaFiscal
     */
    public NotaFiscalView() {
        initComponents();
        popularComboClientes();
        popularComboProdutos();
    }
    
    private void popularComboProdutos() {
        ProdutoController produtoController = new ProdutoController(); 
    try {
        List<Produto> listaProdutos = produtoController.listarProdutos();

        DefaultComboBoxModel<Produto> modelo = new DefaultComboBoxModel<>();
        for (Produto p : listaProdutos) {
            modelo.addElement(p);
        }

        txtProduto.setModel(modelo);

    } catch(FalhaProdutoException e){
        JOptionPane.showMessageDialog(this, "Erro ao carregar os produtos: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    }  catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar os produtos: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    }
}

    
    private void popularComboClientes() {
        ClienteController clienteController = new ClienteController();
    try {
        List<Cliente> listaClientes = clienteController.listarClientes();

        DefaultComboBoxModel<Cliente> modelo = new DefaultComboBoxModel<>();
        for (Cliente c : listaClientes) {
            modelo.addElement(c);
        }

        txtCliente.setModel(modelo);
    } catch(FalhaClienteException e){
        JOptionPane.showMessageDialog(this, "Erro ao carregar os clientes : " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    }
    catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar os clientes : " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        painelClientes = new javax.swing.JPanel();
        btnAdicionarNF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnListarNotas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDataEmissao = new javax.swing.JTextField();
        btnLimparCampos = new javax.swing.JButton();
        btnIrTelaPrincipal = new javax.swing.JButton();
        txtCliente = new javax.swing.JComboBox<>();
        txtProduto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        qtdProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Gerenciamento de NF");

        btnAdicionarNF.setText("Salvar NF");
        btnAdicionarNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarNFActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome Cliente:");

        btnListarNotas.setText("Listar Notas");
        btnListarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarNotasActionPerformed(evt);
            }
        });

        jLabel5.setText("Data Emissão:");

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        btnIrTelaPrincipal.setText("Voltar");
        btnIrTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrTelaPrincipalActionPerformed(evt);
            }
        });

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome Produto:");

        jLabel9.setText("Quantidade:");

        javax.swing.GroupLayout painelClientesLayout = new javax.swing.GroupLayout(painelClientes);
        painelClientes.setLayout(painelClientesLayout);
        painelClientesLayout.setHorizontalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClientesLayout.createSequentialGroup()
                        .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIrTelaPrincipal)
                        .addGap(53, 53, 53))
                    .addGroup(painelClientesLayout.createSequentialGroup()
                        .addComponent(btnLimparCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarNotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarNF, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelClientesLayout.setVerticalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClientesLayout.createSequentialGroup()
                .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClientesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnIrTelaPrincipal))
                    .addGroup(painelClientesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarNotas)
                    .addComponent(btnLimparCampos)
                    .addComponent(btnAdicionarNF))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addComponent(painelClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void limparForms(){
        txtCliente.setSelectedIndex(-1);
        txtProduto.setSelectedIndex(-1);
        qtdProduto.setText("");
    } 
   
    private void btnAdicionarNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarNFActionPerformed
                                              
    try {
     
        Cliente clienteSelecionado = (Cliente) txtCliente.getSelectedItem();
        Produto produtoSelecionado = (Produto) txtProduto.getSelectedItem();

        if (clienteSelecionado == null || produtoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione cliente e produto!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }


        int quantidade = Integer.parseInt(qtdProduto.getText());

        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double valorTotal = produtoSelecionado.getPrecoVenda() * quantidade;
        String dataStr = txtDataEmissao.getText(); 
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date utilDate = sdf.parse(dataStr);
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        
        NotaFiscal nf = new NotaFiscal();
        nf.setCliente(clienteSelecionado);
        nf.setProduto(produtoSelecionado);
        nf.setQuantidade(quantidade);
        nf.setDataEmissao(sqlDate);
        nf.setValorTotal(valorTotal);

       
        NotaFiscalController controller = new NotaFiscalController();
        controller.criarNotaFiscal(nf);

        JOptionPane.showMessageDialog(this, "Nota Fiscal criada com sucesso!");

      
        qtdProduto.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantidade inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (AtualizacaoEstoqueNegativaException e){
         JOptionPane.showMessageDialog(this, "Erro ao criar nota fiscal: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (FalhaNotaFiscalException e){
        JOptionPane.showMessageDialog(this, "Erro ao criar nota fiscal: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    } catch (FalhaProdutoException e ) {
        JOptionPane.showMessageDialog(this, "Erro ao criar nota fiscal: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    } catch (NaoEncontradoException e){
        JOptionPane.showMessageDialog(this, "Erro ao criar nota fiscal: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao criar nota fiscal: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAdicionarNFActionPerformed

    private void btnListarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarNotasActionPerformed
        ListagemNF listagemNotas = new ListagemNF();
        listagemNotas.setVisible(true);
        try {
            NotaFiscalController nfController = new NotaFiscalController();
            List<NotaFiscal> notasFiscais = nfController.listarNotasFiscais();

            DefaultTableModel modelo = (DefaultTableModel) listagemNotas.tabelaNotas.getModel();// Padrão q a internet recomenda, qualquer coisa trocar depois.
            modelo.setRowCount(0);

            for (NotaFiscal nf : notasFiscais) {
                ProdutoService produtoService = new ProdutoService();
                ClienteService clienteService = new ClienteService();
                DecimalFormat df = new DecimalFormat("R$ #,##0.00");
                modelo.addRow(new Object[]{
                  
                     nf.getIdNotaFiscal(),
                     nf.getCliente().getNomeCliente(),
                     nf.getProduto().getNomeProduto(),
                     nf.getDataEmissao(),
                     nf.getQuantidade(),
                     df.format(nf.getValorTotal())
                });
            }

        } catch(FalhaNotaFiscalException e){
            JOptionPane.showMessageDialog(this, "Erro ao listar notas fiscais: " +e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar notas fiscais: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarNotasActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
           limparForms();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnIrTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrTelaPrincipalActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();

        telaPrincipal.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnIrTelaPrincipalActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiscalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiscalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarNF;
    private javax.swing.JButton btnIrTelaPrincipal;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnListarNotas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel painelClientes;
    private javax.swing.JTextField qtdProduto;
    private javax.swing.JComboBox<Cliente> txtCliente;
    private javax.swing.JTextField txtDataEmissao;
    private javax.swing.JComboBox<Produto> txtProduto;
    // End of variables declaration//GEN-END:variables

    private Cliente buscarClientePorNome(String nomeCliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
